#!/usr/bin/env bash
# Build dist/: concatenate CSS (brand tokens first), copy JS, fonts and logo. No tooling needed.
set -euo pipefail
here="$(cd "$(dirname "$0")/.." && pwd)"
brand="$here/../brand"
out="$here/dist"
mkdir -p "$out/fonts"
{
  echo "/* ZAKPY front-end. Generated by scripts/build.sh, do not edit. */"
  cat "$here/css/00-fonts.css"
  echo "/* brand/tokens/tokens.css */"
  cat "$brand/tokens/tokens.css"
  for f in 02-semantic 03-base 04-layout 05-components 06-utilities 07-intro 08-loader; do cat "$here/css/$f.css"; done
} > "$out/zakpy.css"
cp "$here/js/zakpy.js" "$out/zakpy.js"
cp "$brand"/fonts/*.woff2 "$out/fonts/"
cp "$brand/logos/logo_main_transparent.png" "$out/logo.png"
# Icon sprite: one <symbol> per brand/icons/*.svg (file name = id). Use <svg class="icon"><use href="zakpy-icons.svg#home"/></svg>
{
  echo '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">'
  for f in "$brand"/icons/*.svg; do
    id="$(basename "$f" .svg)"
    inner="$(sed -e 's/^<svg[^>]*>//' -e 's/<\/svg>$//' "$f")"
    echo "<symbol id=\"$id\" viewBox=\"0 0 24 24\">$inner</symbol>"
  done
  echo '</svg>'
} > "$out/zakpy-icons.svg"
echo "Built $out ($(wc -c < "$out/zakpy.css") bytes css)"
